### ISSUE TITLE
Add buttom make some views disappearing

### ISSUE THREAD

**Issue by gerchicov-bp** [stefanceriu/SCSafariPageController#3]
Steps to reproduce:
1. add a lot of elements
2. scroll to the most top
3. enable "slow animations" in the simulator
4. press "add" button

Expected result: the control scrolls to the last element and unfolds it simultaneously with animation (or at least it scrolls then at the end of animation unfolds).
Actual result: some elements disappear, some ones perform unfolding animation. No animated scrolling.

**Comment by stefanceriu** [comment]
Slow simulator animations don't apply to CADisplayLinks (the thing that powers scrolling).
What you are seeing is a really slow insertion animation and then a fast scroll to the bottom as the animations are out of sync.
You are also seeing missing pages because the scroll view is traveling over a very big distance in a short time, trying to cycle pages along the way and not managing to do it in time for all of them.

You can trick it into not doing that doing an animated navigation first, and then inserting, similar to this:

```objc
[self.safariPageController navigateToPageAtIndex:self.dataSource.count - 1 animated:YES completion:^{
		
		[self.dataSource insertObject:[NSNull null] atIndex:self.safariPageController.numberOfPages];
		
		[self.safariPageController insertPagesAtIndexes:[NSIndexSet indexSetWithIndex:self.safariPageController.numberOfPages] animated:YES completion:^{
			[self _toggleZoomWithPageIndex:(self.safariPageController.numberOfPages - 1)];
		}];
	}];
```
